steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'config/Dockerfile.worker', '-t', 'gcr.io/securemed-ai/mednotes-worker', '.']
images:
  - 'gcr.io/securemed-ai/mednotes-worker'
